import Head from 'next/head'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import About from './about'
import HomePage from './home'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Rafael de Siqueira</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <HomePage/>
      <About/>
      <Footer/>
    </div>
  )
}
